port: 5001
docker_token: <placeholder>
output_dir: "./"
kube_config: "/Users/igoreulalio/.kube/config"
namespace: default
#cache:
#  redis:
#    port:
#    password:
#    database:
#  local:
#    expiration: 10
#    max_size: 100