kube_config: "/Users/igoreulalio/.kube/config"
port: 5001
docker_token: <placeholder>
output_dir: "./"
namespace: default
tls_cert_file: /Users/igoreulalio/sysdig/personal-projects/trivy-admission-controller/certs/server.crt
tls_key_file: /Users/igoreulalio/sysdig/personal-projects/trivy-admission-controller/certs/server.key
#cache:
#  redis:
#    port:
#    password:
#    database:
#  local:
#    expiration: 10
#    max_size: 100