apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "trivy-admission-controller.configMapName" . }}
data:
  {{ include "trivy-admission-controller.configFileName" . }}: |
    {{ toYaml .Values.config | nindent 4 }}
