apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: scannedimages.trivyac.io
spec:
  group: trivyac.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                imageDigest:
                  type: string
                allowed:
                  type: boolean
                imagePullString:
                  type: string
  scope: Namespaced
  names:
    plural: scannedimages
    singular: scannedimage
    kind: ScannedImage
    shortNames:
      - si