apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "trivy-admission-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trivy-admission-controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "trivy-admission-controller.serviceAccountName" . }}-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trivy-admission-controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: ["trivyac.io"]
    resources: ["scannedimages"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["v1"]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "trivy-admission-controller.serviceAccountName" . }}-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trivy-admission-controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "trivy-admission-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "trivy-admission-controller.serviceAccountName" . }}-role
  apiGroup: rbac.authorization.k8s.io